name: Build and deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
          cache: yarn
          cache-dependency-path: infra/yarn.lock
      - uses: docker/setup-buildx-action@v2
      - uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: 'projects/429303088514/locations/global/workloadIdentityPools/deploy/providers/github'
          service_account: 'pulumi-account@lferraz-personal-servers-1.iam.gserviceaccount.com'

      - run: gcloud auth configure-docker

      - uses: docker/build-push-action@v2
        with:
          context: .
          tags: gcr.io/lferraz-personal-servers-1/francis-server:latest
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - uses: pulumi/actions@v3
        with:
          command: up
          stack-name: Fryuni/francis-server/dev
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
